version: '2'

services:
    nginx: 
        image: nginx
        restart: unless-stopped
        ports:
            - $OCRV_RECORDER_MAIN_PORT:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./ocrv/served:/served
            - ./ocrv/recordings:/served/recordings
        depends_on: 
            - backend
            - frontend

    backend:
        restart: unless-stopped
        env_file: 
            backend_env
        environment: 
            - OCRV_RECORDER_RECORDINGS_URL=/recordings/
            - OCRV_RECORDER_STATIC_URL=/django_static/
            - OCRV_RECORDER_STATIC_ROOT=/app/var/served/django_static
            - OCRV_RECORDER_TEXTS_PATH=/app/var/texts.csv
            - OCRV_RECORDER_RECORDINGS_DIR=/app/var/recordings/
            - OCRV_RECORDER_LOG_PATH=/app/var/logs.log
            - OCRV_RECORDER_DB_PATH=/app/var/db.sqlite3
        build:
            context: ./backendV2
            dockerfile: ./deploy/Dockerfile
        volumes:
            - ./ocrv:/app/var

    frontend:
        restart: unless-stopped
        build:
            context: ./web-frontend
            dockerfile: ./Dockerfile
